project_name: otel-go-dcp

release:
  github:
    name: otel-go-dcp
    owner: Trendyol

before:
  hooks:
    - go mod tidy

builds:
  - skip: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^docs:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy