name: Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Start tracing infra
        run: docker compose -f development/docker-compose.otel-jaeger.yml up -d

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Integration Test
        run: cd test/integration/basic-otel-tracing && go test -v ./...
        env:
          INPUT_PUBLISH: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete tracing infra
        run: docker compose -f development/docker-compose.otel-jaeger.yml down

